---
- hosts: all
  
  become: yes
  environment: 
    PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}: /home/vagrant/.local/lib/python3.6/site-packages"
  tasks:

  # Install Docker
  # --
  # 
  - name: install prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      update_cache: yes

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker 
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

  - name: add userpermissions
    shell: "usermod -aG docker vagrant"

  # Installs Docker SDK
  # --
  # 
  - name: install python package manager
    apt:
      name: python3-pip

  - name: install python sdk
    become_user: "vagrant"
    pip:
      executable: pip3
      extra_args: --upgrade
      name:
        - docker
        - docker-compose