---
- name: Start load testing
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Run load tests
      include_tasks: stats_loops.yml
      loop:
        - 100
        - 500
        - 1000
        - 5000
