---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Create server container
      docker_container:
        name: server1
        image: aos_server
        networks:
          - name: mynet
            aliases:
              - server
    - name: Create client container
      docker_container:
        name: client1
        image: aos_client_go
        detach: yes
        tty: yes
        interactive: yes
        networks:
          - name: mynet