---
- name: Start load testing
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Run load tests
      include_tasks: testing_with_item.yaml
      loop:
        - 100
        - 1000
        - 10000
